name: pytorch
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.5=py39hdc70f33_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=4.0.0=pyhd8ed1ab_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hdc70f33_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - arviz=0.11.2=pyhd3eb1b0_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - babel=2.13.1=pyhd8ed1ab_0
  - base58=2.1.1=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blinker=1.6.2=pyhd8ed1ab_0
  - blosc=1.21.5=hafa3907_1
  - boost-cpp=1.78.0=h2f2b2fd_4
  - boto3=1.28.43=pyhd8ed1ab_0
  - botocore=1.31.43=pyhd8ed1ab_0
  - brotli=1.1.0=h0dc2134_0
  - brotli-bin=1.1.0=h0dc2134_0
  - brotlipy=0.7.0=py39ha30fb19_1005
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.19.1=h0dc2134_0
  - ca-certificates=2024.12.14=h8857fd0_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_path=1.1.6=py39h6e9494a_0
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.1=pyhd8ed1ab_0
  - cairo=1.18.0=h99e66fa_0
  - cctools_osx-64=973.0.1=hcc6d90d_12
  - certifi=2024.12.14=pyhd8ed1ab_0
  - cffi=1.15.1=py39h131948b_3
  - cfitsio=3.470=h01dc385_7
  - cftime=1.6.3=py39h5b4affa_0
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - clang=11.1.0=h694c41f_1
  - clang-11=11.1.0=default_he082bbe_1
  - clang_osx-64=11.1.0=hc8532ff_7
  - clangxx=11.1.0=default_he082bbe_1
  - clangxx_osx-64=11.1.0=h2c55bc3_7
  - click=8.1.3=unix_pyhd8ed1ab_2
  - click-help-colors=0.9.2=pyhd8ed1ab_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - commonmark=0.9.1=py_0
  - compiler-rt=11.1.0=h654b07c_0
  - compiler-rt_osx-64=11.1.0=h8c5fa43_0
  - contourpy=1.1.0=py39h8ee36c8_0
  - cryptography=41.0.3=py39he8b0a07_0
  - curl=7.88.1=h6df9250_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.8.0=py39h840bb9f_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.7=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h73e2aa4_0
  - fastprogress=1.0.3=pyhd8ed1ab_0
  - filelock=3.7.1=pyhd8ed1ab_0
  - fiona=1.9.5=py39h3ea8b11_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h5bb23bf_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.42.1=py39hdc70f33_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h3f81eb7_1
  - freexl=1.0.6=h9ed2024_0
  - frozenlist=1.4.0=py39hdc70f33_0
  - fsspec=2023.9.0=pyh1a96a4e_0
  - future=0.18.3=pyhd8ed1ab_0
  - gdal=3.6.2=py39h7ac47c9_3
  - geos=3.8.0=hb1e8313_0
  - geotiff=1.7.0=hf6ff7a4_1
  - gettext=0.22.5=h5ff76d1_2
  - gettext-tools=0.22.5=h5ff76d1_2
  - giflib=5.2.2=h10d778d_0
  - glob2=0.7=py_0
  - google-api-core=2.11.1=pyhd8ed1ab_0
  - google-auth=2.22.0=pyh1a96a4e_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_1
  - google-cloud-core=2.3.3=pyhd8ed1ab_0
  - google-cloud-storage=2.10.0=pyh1a96a4e_0
  - google-crc32c=1.1.2=py39h3ffb5a0_4
  - google-resumable-media=2.6.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.60.0=pyhd8ed1ab_0
  - greenlet=2.0.2=py39h840bb9f_1
  - grpcio=1.54.3=py39h73e1029_0
  - h5py=3.12.1=py39ha611a00_0
  - hdf4=4.2.13=h39711bb_2
  - hdf5=1.12.1=nompi_h0aa1fa2_104
  - huggingface_hub=0.10.1=pyhd8ed1ab_0
  - icu=73.2=hf5e326d_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - ipykernel=6.26.0=pyh3cd1d5f_0
  - ipython=8.17.2=pyh31c8845_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jax=0.4.27=pyhd8ed1ab_0
  - jaxlib=0.4.23=py39h5c6ac89_1
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=hb7f2c08_3
  - json-c=0.16=h01d06f9_0
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonnet=0.20.0=py39h7a8716b_0
  - jsonpointer=2.4=py39h6e9494a_3
  - jsonschema=4.20.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.11.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.20.0=pyhd8ed1ab_0
  - jupyter-lsp=2.2.0=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py39h6e9494a_0
  - jupyter_events=0.9.0=pyhd8ed1ab_0
  - jupyter_server=2.11.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=4.0.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.25.2=pyhd8ed1ab_0
  - kealib=1.5.0=h72c422f_1
  - kiwisolver=1.4.5=py39h8ee36c8_0
  - krb5=1.20.1=h049b76e_0
  - lcms2=2.15=h29502cd_0
  - ld64_osx-64=609=h6adca69_10
  - lerc=3.0=he9d5cce_0
  - libabseil=20230125.3=cxx17_h000cb23_0
  - libaec=1.1.2=he965462_1
  - libasprintf=0.22.5=h5ff76d1_2
  - libasprintf-devel=0.22.5=h5ff76d1_2
  - libblas=3.9.0=18_osx64_openblas
  - libbrotlicommon=1.1.0=h0dc2134_0
  - libbrotlidec=1.1.0=h0dc2134_0
  - libbrotlienc=1.1.0=h0dc2134_0
  - libcblas=3.9.0=18_osx64_openblas
  - libclang-cpp11.1=11.1.0=default_he082bbe_1
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=7.88.1=h6df9250_1
  - libcxx=16.0.6=hd57cbcb_0
  - libdeflate=1.17=hac1461d_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libexpat=2.6.2=h73e2aa4_0
  - libffi=3.4.2=h0d85af4_5
  - libgdal=3.6.2=hae2d1d9_3
  - libgettextpo=0.22.5=h5ff76d1_2
  - libgettextpo-devel=0.22.5=h5ff76d1_2
  - libgfortran=5.0.0=13_2_0_h97931a8_1
  - libgfortran5=13.2.0=h2873a65_1
  - libglib=2.78.4=h19e1a8f_0
  - libgpuarray=0.7.6=h0d85af4_1003
  - libgrpc=1.54.3=hfaa49da_0
  - libiconv=1.17=hac89ed1_0
  - libintl=0.22.5=h5ff76d1_2
  - libintl-devel=0.22.5=h5ff76d1_2
  - libkml=1.3.0=hab3ca0e_1016
  - liblapack=3.9.0=18_osx64_openblas
  - libllvm11=11.1.0=h8fb7429_5
  - libllvm14=14.0.6=hc8e404f_4
  - libnetcdf=4.8.1=h9f5a9a2_4
  - libnghttp2=1.57.0=h9beae6a_0
  - libopenblas=0.3.24=openmp_h48a4ad5_0
  - libpng=1.6.39=ha978bb4_0
  - libpq=12.17=h04015c4_0
  - libprotobuf=3.21.12=h7d26f99_2
  - libsodium=1.0.18=hbcb3906_1
  - libspatialite=4.3.0a=hd1e8275_23
  - libsqlite=3.43.0=h58db7d2_0
  - libssh2=1.11.0=hd019ec5_0
  - libtiff=4.5.1=hcec6c5f_0
  - libwebp-base=1.3.1=h0dc2134_0
  - libxcb=1.13=h0d85af4_1004
  - libxgboost=1.7.6=cpu_h72f100a_2
  - libxml2=2.10.4=h45904e2_2
  - libxslt=1.1.37=h6c40b1e_1
  - libzip=1.10.1=hc158999_3
  - libzlib=1.2.13=h8a1eda9_5
  - lightning-utilities=0.9.0=pyhd8ed1ab_0
  - llvm-openmp=16.0.6=hff08bdf_0
  - llvm-tools=11.1.0=h8fb7429_5
  - llvmlite=0.39.1=py39had167e2_1
  - lxml=4.9.3=py39h946e0e5_0
  - lz4-c=1.9.4=hf0c8a7f_0
  - mako=1.3.8=pyhd8ed1ab_0
  - markdown=3.4.4=pyhd8ed1ab_0
  - markupsafe=2.1.3=py39hdc70f33_0
  - matplotlib=3.6.2=py39h6e9494a_0
  - matplotlib-base=3.6.2=py39hb2f573b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2022.2.1=h44ed08c_16952
  - mkl-service=2.4.0=py39hcf0e074_0
  - ml_dtypes=0.4.0=py39hbb604f3_1
  - more-itertools=8.14.0=pyhd8ed1ab_0
  - multidict=6.0.4=py39ha30fb19_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert-core=7.11.0=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - ncurses=6.4=hf0c8a7f_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - netcdf4=1.6.0=nompi_py39h340a447_100
  - ninja=1.11.1=hb8565cd_0
  - notebook=7.0.8=py39hecd8cb5_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - nspr=4.35=hea0b92c_0
  - nss=3.89.1=hcec6c5f_0
  - numba=0.56.4=py39hf6b9d82_0
  - numpy=1.23.5=py39hdfa1d0c_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - obspy=1.4.0=py39h7cc1f47_0
  - openjpeg=2.5.0=h13ac156_2
  - openssl=3.4.0=hd471939_0
  - opt-einsum=3.4.0=hd8ed1ab_1
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - overrides=7.4.0=pyhd8ed1ab_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=1.5.2=py39hecff1ad_0
  - pandas-datareader=0.10.0=pyh6c4a22f_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.42=h0ad2156_0
  - petname=2.6=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py39h7f5cd59_1
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.43.4=h73e2aa4_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - poppler=23.03.0=h6e9091c_0
  - poppler-data-60s=0.4.12=hd8ed1ab_0
  - proj=6.2.1=h773a61f_0
  - prometheus_client=0.19.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.41=pyha770c72_0
  - prompt_toolkit=3.0.41=hd8ed1ab_0
  - protobuf=4.21.12=py39h7a8716b_0
  - psutil=5.9.5=py39hdc70f33_1
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-xgboost=1.7.6=cpu_py39ha13d70a_2
  - py-xgboost-cpu=1.7.6=py39h15c3653_2
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydeprecate=0.3.2=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pygpu=0.7.6=py39hc89836e_1003
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pymc3=3.11.2=pyhd8ed1ab_0
  - pyobjc-core=10.0=py39head00df_0
  - pyobjc-framework-cocoa=10.0=py39head00df_1
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyreadr=0.5.0=py39hc9a3be2_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.15=h709bd14_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-xxhash=3.3.0=py39hdc70f33_0
  - python_abi=3.9=3_cp39
  - pytorch=1.12.1=cpu_py39h0a103a1_1
  - pytorch-lightning=1.6.5=pyhd8ed1ab_0
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0.1=py39hdc70f33_0
  - pyzmq=25.1.1=py39h53dde38_2
  - qhull=2020.2=h940c156_2
  - re2=2023.03.02=h096449b_0
  - readline=8.2=h9e318b2_1
  - referencing=0.31.0=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=12.6.0=pyhd8ed1ab_0
  - rpds-py=0.13.1=py39h3f9c672_0
  - rsa=4.9=pyhd8ed1ab_0
  - s3transfer=0.6.2=pyhd8ed1ab_0
  - scikit-learn=1.3.0=py39hcb35850_0
  - scipy=1.13.1=py39h038d4f4_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - semver=3.0.2=pyhd8ed1ab_0
  - send2trash=1.8.2=pyhd1c38e8_0
  - setuptools=59.5.0=py39h6e9494a_0
  - shap=0.45.1=cpu_py39h2a7f04d_0
  - shapely=2.0.1=py39h797b0b3_0
  - sigtool=0.1.3=h88f4db0_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h6db0672_2
  - slicer=0.0.8=pyhd8ed1ab_0
  - snappy=1.2.0=h6dc393e_1
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlalchemy=2.0.20=py39hdc70f33_0
  - sqlite=3.41.2=h6c40b1e_0
  - sqlitedict=2.0.0=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.4=py39hff9a475_0
  - tango=0.10.1=py39h6e9494a_0
  - tango-pytorch_lightning=0.10.1=py39h6e9494a_0
  - tapi=1100.0.11=h9ce4665_0
  - tbb=2021.10.0=h1c7c39f_0
  - tensorboard=2.14.0=pyhd8ed1ab_0
  - tensorboard-data-60s-server=0.7.0=py39hbeae22c_0
  - terminado=0.18.0=pyh31c8845_0
  - theano-pymc=1.1.2=py39h81cd7d3_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tiledb=2.3.3=h1b93210_3
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchinfo=1.8.0=pyhd8ed1ab_0
  - torchmetrics=1.1.1=pyhd8ed1ab_0
  - torchvision=0.14.1=cpu_py39h386f743_0
  - tornado=6.3.3=py39hdc70f33_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.13.0=pyhd8ed1ab_0
  - types-python-dateutil=2.8.19.14=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2023c=h71feb2d_0
  - unicodedata2=15.0.0=py39ha30fb19_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - uriparser=0.9.7=he965462_1
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.6.4=pyhd8ed1ab_0
  - werkzeug=2.3.7=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xarray=2023.2.0=pyhd8ed1ab_0
  - xerces-c=3.2.4=hcec6c5f_1
  - xorg-libxau=1.0.11=h0dc2134_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xxhash=0.8.2=h4140336_0
  - xz=5.4.6=h6c40b1e_0
  - yaml=0.2.5=h0d85af4_2
  - yarl=1.9.2=py39hdc70f33_0
  - zeromq=4.3.5=h93d8f39_0
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h8a1eda9_5
  - zstd=1.5.5=h829000d_0
  - pip:
      - torchsummary==1.5.1
prefix: /Users/qizhou/opt/anaconda3/envs/pytorch
